name: Run Add and Remove Elements Test
on:
    workflow_dispatch:
      inputs:
        test_to_run:
          type: choice
          options:
            - add_remove_elements
            - basic_auth
            - broken_images
        browser_to_target:
          type: choice
          options:
            - Chrome
            - Firefox
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.14.3
        - name: Install dependencies
          run: |
            #Install Firefox browser and driver
            if [ ${{inputs.browser_to_target}} -eq 'firefox']: then
              sudo apt-get update
              sudo apt-get install -y firefox   
            
            #Install Chrome browser and driver by default if no other browser is specified
            else
              sudo apt-get update
              sudo apt-get install -y chromium-browser chromium-chromedriver
            fi

            #Install Poetry and Python Dependencies
            curl -sSL https://install.python-poetry.org | python3 -
            poetry config virtualenvs.in-project true
            poetry install  --no-root
        - name: Test Setup - ${{inputs.test_to_run}}
          run: |
            if [${{inputs.test_to_run}} -eq 'basic_auth' ]: then
              mkdirs configs
              touch configs/test_basic_auth.json
              echo ${{secrets.TEST_BASIC_AUTH_CREDENTIALS}} >> configs/test_basic_auth.json
        - name: ${{inputs.test_to_run}} Test - ${{inputs.browser_to_target}}
          run: |
            poetry run python -m pytest SeleniumTests/test_${{inputs.test_to_run}}.py -v --html=results/test_add_remove_elements_$(date +'%s').html --browser=${{inputs.browser_to_target}}
          env:
            CHROME_BIN: /usr/bin/chromium-browser
        - name: Upload results as artifact
          id: deployment
          uses: actions/upload-artifact@v4
          with:
            name: ${{inputs.test_to_run}} Test Results
            retention-days: 30
            path: results/

          
