name: Run Add and Remove Elements Test
on:
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.14.3
        - name: Install dependencies
          run: |
            #Install Chrome browser and driver
            sudo apt-get update
            sudo apt-get install -y chromium-browser chromium-chromedriver
            
            #Install Poetry and Python Dependencies
            curl -sSL https://install.python-poetry.org | python3 -
            poetry config virtualenvs.in-project true
            poetry install  --no-root
        - name: Activate Virtual Environment
          run: |
            source .venv/bin/activate
        - name: Add and Remove Elements Test
          run: |
            python -m pytest SeleniumTests/test_add_remove_elements.py --headless --html=results/test_broken_images-$(date +'%s').html
          env:
            CHROME_BIN: /usr/bin/chromium-browser
        - name: Commit Result Files
          uses: actions-x/commit@v6
          with:
            message: Uploading test results.
            directory: results
          
