name: Run Selenium Test
on:
    workflow_dispatch:
      inputs:
        test_to_run:
          type: choice
          options:
            - add_remove_elements
            - basic_auth
            - broken_images
        browser_to_target:
          type: choice
          options:
            - chrome
            - firefox
jobs:
    selenium-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.14.3
        - name: Install dependencies
          run: |
            # #Install Chrome browser and driver by default if no other browser is specified
            if [ ${{inputs.browser_to_target}} == chrome ]; then
              sudo apt-get update
              sudo apt-get install -y chromium-browser chromium-chromedriver
            fi

            #Install Poetry and Python Dependencies
            curl -sSL https://install.python-poetry.org | python3 -
            poetry config virtualenvs.in-project true
            poetry install  --no-root
        - name: Set test data
          run: |
            if [ ${{inputs.test_to_run}} == basic_auth ]; then
              mkdir configs
              echo ${{secrets.TEST_BASIC_AUTH_CREDENTIALS}} >> configs/test_basic_auth.json
            fi
        - name: ${{inputs.test_to_run}} test - ${{inputs.browser_to_target}}
          run: |
            poetry run python -m pytest SeleniumTests/test_${{inputs.test_to_run}}.py -v --html=results/test_${{inputs.test_to_run}}_$(date +'%s').html --browser='${{inputs.browser_to_target}}' --headless='True'
          env:
            CHROME_BIN: /usr/bin/chromium-browser
        - name: Upload results as artifact
          id: deployment
          uses: actions/upload-artifact@v4
          with:
            name: ${{inputs.test_to_run}} Test Results
            retention-days: 30
            path: results/

          
