name: Run All Tests
on:
    workflow_dispatch:
        inputs:
            category_to_run:
                type: choice
                options:
                  - selenium
                  - api
                  - all
jobs:
    api-tests:
        if: ${{(inputs.category_to_run == 'api') || (inputs.category_to_run == 'all')}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.14.3
            - name: Install Dependencies
              run: |
                #Install Poetry and Dependencies
                curl -sSL https://install.python-poetry.org | python3 -
                poetry config virtualenvs.in-project true
                poetry install --no-root
            - name: Run API Tests
              run: |
                poetry run python -m pytest APITests/ --html=results/all_api_tests_$(date +'%s').html
            - name: Upload results as artifact
              id: deployment
              uses: actions/upload-artifact@v4
              with:
                name: API Test Results
                retention-days: 30
                path: results/
    selenium-tests:
        if: ${{(inputs.category_to_run == 'api') || (inputs.category_to_run == 'all')}}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.14.3
            - name: Install Dependencies
              run: |
                #Install Chrome Browser and Driver
                sudo apt-get update
                sudo apt-get install -y chromium-browser chromium-chromedriver

                #Install Poetry and Python Dependencies
                poetry config virtualenvs.in-project true
                poetry install --no-root
            - name: Setup Test Data
              run: |
                mkdir configs
                # Add basic_auth credentials
                touch configs/test_basic_auth.json
                echo ${{secrets.TEST_BASIC_AUTH_CREDENTIALS}} >> configs/test_basic_auth.json
            - name: Run Tests in Chrome
              run: |
                poetry run -m pytest SeleniumTests/ -v --html=results/all_selenium_tests_(date +'%s').html --browser='chrome' --headless='True'
            - name: Run Tests in Firefox
              run: |
                poetry run -m pytest SeleniumTests/ -v --html=results/all_selenium_tests_(date +'%s').html --browser='firefox' --headless='True'
            - name: Upload Results as Artifact
              uses: actions/upload-artifact@v4  
              with:
                name: Selenium Test Results
                retention-days: 30
                path: results/




        
    
